name: Deploy Laravel to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: DOT_ENV

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Masuk ke folder, jika gagal (belum ada), clone dulu
          if [ ! -d "/var/www/html/my-app/.git" ]; then
            cd /var/www/html
            git clone https://github.com/${{ github.repository }}.git my-app
          fi

          cd /var/www/html/my-app

          # Reset kode ke versi terbaru dari GitHub
          git fetch origin main
          git reset --hard origin/main

          # Pasang konfigurasi .env
          echo "${{ secrets.ENV_CONTENTS }}" > .env

          # Jalankan Composer dengan Full Path
          /usr/local/bin/composer install --no-interaction --prefer-dist --optimize-autoloader

          # Jalankan Artisan dengan Full Path
          /usr/bin/php artisan migrate --force
          /usr/bin/php artisan config:cache
          /usr/bin/php artisan route:cache

          # Atur Permission (Opsional jika user SSH adalah root)
          # sudo chown -R www-data:www-data storage bootstrap/cache
